import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

// Clerk
import { ClerkProvider } from '@clerk/nextjs'
import { ptBR } from '@clerk/localizations'

// Tema
import { ThemeProvider } from '@/components/providers/theme-provider'
// Modal
import { ModalProvider } from '@/components/providers/modal-provider'
// Socket.io Conexão Bate-papo 
import { SocketProvider } from '@/components/providers/socket-provider'
// Query Tanstack
import { QueryProvider } from '@/components/providers/query-provider'

import { cn } from '@/lib/utils'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Team Chat Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(
          "bg-white dark:bg-[#313338]",
          font.className
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="discord-theme"
          >
            <SocketProvider>
              <ModalProvider />
              <QueryProvider>
                {children}
              </QueryProvider>
            </SocketProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
